#!/usr/bin/env python

import server
import getopt
import sys
import file_utils
import os
import config
from multiprocessing import cpu_count

try:
    opts, args = getopt.getopt(sys.argv[1:], "r:c:")
except getopt.GetoptError:
    print 'error in arguments'
    sys.exit()

for opt, arg in opts:
    if opt == '-r':
        config.document_root = arg
        if not os.access(arg, os.R_OK):
            print 'could not access document_root'
            sys.exit()
        if config.DOCUMENT_ROOT.endswith('/'):
            config.document_root = config.DOCUMENT_ROOT[:-1]
    elif opt == '-c':
        arg = int(arg)
        if arg not in range(1, cpu_count() + 1):
            print 'cores number out of range'
            sys.exit()
        config.cores = arg


serv = server.Server()
serv.run()
